# Generated by Django 3.0.5 on 2020-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0003_auto_20200905_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='image/profile_pics/'),
        ),
    ]
