from django.urls import path, re_path, include
from django.views.generic import TemplateView
from .views import (
   Index,
   TestDataList,
   TestDataDetail,
   QuestionList,
   QuestionDetail,
   GroupList,
   GroupDetail,
   ImageList,
   ImageDetail,
   AllTestList,
   MyTestList,
   MyTestDetail,
   TestQuestions,
   ValidateAccess,
   SubmitTest,
   ResultList,
   AllSiteGroupList,
   MySiteGroupList,
   MySiteGroupDetail,
   AnswerFileUpload,
   PenddingTest,
   MarkTest,
   GroupUserList,
   GroupUserDetail,
   GroupAccess,
   GroupAdmission,
   Statistics,
)

urlpatterns = [
   path('test/', TestDataList.as_view(), name="test_data_list"),
   path('test/<int:pk>/', TestDataDetail.as_view(), name="test_data_detail"),
   path('test/<int:testid>/question/', QuestionList.as_view(), name="question_list"),
   path('test/<int:testid>/question/<int:pk>/', QuestionDetail.as_view(), name="question_detail"),
   path('test/<int:testid>/group/', GroupList.as_view(), name="group_list"),
   path('test/<int:testid>/group/<int:pk>/', GroupDetail.as_view(), name="group_detail"),
   path('test/<int:testid>/image/', ImageList.as_view(), name="image_list"),
   path('test/<int:testid>/image/<int:pk>/', ImageDetail.as_view(), name="image_detail"),
   path('alltest/', AllTestList.as_view(), name="all_test_list"),
   path('mytest/', MyTestList.as_view(), name="my_test_list"),
   path('mytest/<int:pk>/', MyTestDetail.as_view(), name="mytest_detail"),
   path('mytest/group/<int:id>/', MyTestList.as_view(), name="my_group_test_list"),
   path('allgroup/', AllSiteGroupList.as_view(), name="all_sitegroup_list"),
   path('mygroup/', MySiteGroupList.as_view(), name="my_sitegroup_list"),
   path('mygroup/<int:pk>/', MySiteGroupDetail.as_view(), name="my_sitegroup_detail"),
   path('mygroup/<int:pk>/user/',  GroupUserList.as_view(), name="group_user"),
   path('mygroup/<int:group_id>/user/<int:pk>/',  GroupUserDetail.as_view(), name="romove_group_user"),
   path('group_access/<int:group_id>/',  GroupAccess.as_view(), name="group_access"),
   path('group_admission/<int:group_id>/',  GroupAdmission.as_view(), name="group_admission"),
   path('result/', ResultList.as_view(), name="result"),
   path('result/group/<int:pk>/', ResultList.as_view(), name="group_result"),
   path('testquestions/', TestQuestions.as_view(), name="test_questions"),
   path('validatepassword/', ValidateAccess.as_view(), name="validate_password"),
   path('submittest/', SubmitTest.as_view(), name="submit_test"),
   path('answerfileupload/', AnswerFileUpload.as_view(), name="answer_upload"),
   path('penddingtest/', PenddingTest.as_view(), name="pendding_test"),
   path('marktest/', MarkTest.as_view(), name="mark_test"),
   path('statistics/', Statistics.as_view(), name="statistics"),
]