# Generated by Django 3.0.5 on 2020-10-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0002_auto_20201018_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
