# Generated by Django 3.0.5 on 2020-10-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0003_question_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fill_answer_scheme',
            new_name='mark_scheme',
        ),
    ]
