# Generated by Django 3.0.5 on 2020-10-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0004_auto_20201018_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('OPTION', 'option'), ('FILL', 'fill'), ('FILE', 'file')], default='OPTION', max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('DOC', 'Doc'), ('PDF', 'Pdf')], default='IMAGE', max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
