# Generated by Django 3.0.5 on 2020-10-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0005_auto_20201019_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testme.TestData'),
        ),
    ]
