# Generated by Django 3.0.5 on 2020-10-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0007_auto_20201019_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
