# Generated by Django 3.0.5 on 2020-10-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0008_delete_questionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
