# Generated by Django 3.0.5 on 2020-10-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0010_auto_20201022_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='answer_question',
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(through='testme.QuestionOptions', to='testme.Answer'),
        ),
    ]
