# Generated by Django 3.0.5 on 2020-10-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0013_auto_20201022_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='test_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testme.TestData'),
        ),
    ]
