# Generated by Django 3.0.5 on 2020-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0014_auto_20201024_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
