# Generated by Django 3.0.5 on 2020-10-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0016_questionimages_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimages',
            name='image',
            field=models.ImageField(upload_to='media/image/question_images/'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='cover_image',
            field=models.FileField(upload_to='media/image/test_cover/'),
        ),
    ]
