# Generated by Django 3.0.5 on 2020-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0017_auto_20201026_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='test_attempts',
            new_name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='question_attemptable',
        ),
        migrations.AddField(
            model_name='testdata',
            name='questions_attemptable',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='image',
            field=models.ImageField(upload_to='image/question_images/'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='image/test_cover/'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='rewrite_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=11),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
