# Generated by Django 3.0.5 on 2020-10-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0018_auto_20201027_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimages',
            name='test_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testme.TestData'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testme.TestData'),
            preserve_default=False,
        ),
    ]
