# Generated by Django 3.0.5 on 2020-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0020_auto_20201031_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionImages',
            new_name='QuestionImage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='result',
            name='finish_timeinsec',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdata',
            name='exclusive_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testdata',
            name='view_result',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='mark_scheme',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdata',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
