# Generated by Django 3.0.5 on 2020-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0021_auto_20201117_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_complete',
            new_name='valid_question',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='exclusive_test',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='questions_attemptable',
        ),
        migrations.AddField(
            model_name='testdata',
            name='valid_questions',
            field=models.IntegerField(default=0),
        ),
    ]
