# Generated by Django 3.0.5 on 2020-11-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0023_auto_20201121_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
