# Generated by Django 3.0.5 on 2020-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0025_auto_20201129_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='finish_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
