# Generated by Django 3.0.5 on 2020-12-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0026_auto_20201129_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/test_cover/'),
        ),
    ]
