# Generated by Django 3.0.5 on 2020-12-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0027_auto_20201215_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='submission_date',
            new_name='started',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='finish_time',
            new_name='time_elapsed',
        ),
        migrations.RenameField(
            model_name='testdata',
            old_name='per_mark',
            new_name='points_per_mark',
        ),
        migrations.RemoveField(
            model_name='result',
            name='upload_links',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='rewrite_test',
        ),
        migrations.AddField(
            model_name='result',
            name='submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='allowed_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testdata',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='question_per_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testdata',
            name='randomize_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='AnswerUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='answer_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.Result')),
                ('test_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.TestData')),
            ],
        ),
    ]
