# Generated by Django 3.0.5 on 2020-12-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0028_auto_20201220_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='result',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
