# Generated by Django 3.0.5 on 2021-01-04 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testme.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testme', '0030_auto_20201227_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='fill_data',
        ),
        migrations.AddField(
            model_name='answerupload',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testme.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_delta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answerupload',
            name='file',
            field=models.FileField(upload_to='answer_files/', validators=[testme.validators.answer_upload_validator]),
        ),
        migrations.CreateModel(
            name='AnswerFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.Question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.Result')),
                ('test_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testme.TestData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
