# Generated by Django 3.0.5 on 2021-01-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0031_auto_20210104_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitegroup',
            name='general',
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='access',
            field=models.CharField(choices=[('General', 'General Access'), ('Members', 'Members Only')], default='Members', max_length=7),
        ),
    ]
