# Generated by Django 3.0.5 on 2021-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0032_auto_20210104_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerupload',
            name='file',
            field=models.FileField(upload_to='answer_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(upload_to='image/question_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/test_cover/%Y/%m/%d/'),
        ),
    ]
