# Generated by Django 3.0.5 on 2021-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0033_auto_20210107_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegroup',
            name='access_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
